### ISSUE TITLE
how to call sarcasm_test().use_neural_network("") for multiple times.

### ISSUE THREAD

**Issue by Bipulkumarsingh** [savithakj/sarcasmDetection#1]
i am trying to sent_tokenize() long paragraph and then sending single tokens using for loop , but it's not working, because above module is called only for single time.

**Comment by savithakj** [comment]
In order to test the neural network model several times, you can use the function in this way

` from sarcasm_test import sarcasm_test
testObject=sarcasm_test()
testObject.use_neural_network("Going to the gym ?")
testObject.use_neural_network("Why dont you understand what I say!")
`
